import Head from "next/head";
import DropdownMenu from "../../../components/Sidebar";
import React, { useState, useEffect } from "react";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/router";
import PokemonStats from "../../../components/PokemonStats";
import { types, hexToGrayscale } from "../../../functions/color";

export default function PokemonDetails() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [pokemon, setPokemon] = useState([]);
  const [details, setDetails] = useState([]);
  const [description, setDescription] = useState([]);
  const { name } = router.query;

  useEffect(() => {
    if (router.isReady) {
      axios
        .get(`https://pokeapi.co/api/v2/pokemon/${name}`)
        .then((res) => {
          const getPokemon = async () => {
            try {
              setPokemon(res.data);
              axios.get(res.data.species.url).then((res) => {
                const getDetails = async () => {
                  setDetails(res.data);
                  setDescription(
                    res.data.flavor_text_entries.filter(function (el) {
                      return el.language?.name == "en";
                    })
                  );
                };
                getDetails();
              });
            } catch (err) {
              console.log(err);
            }
          };
          getPokemon();
        })
        .catch((err) => console.log(err));
    }
  }, [router.isReady]);
  return (
    <div>
      <Head>
        <title>PokéStop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DropdownMenu open={open} setOpen={setOpen} />

      {/* <div className="bg-[url('../public/assets/background.jpg')] bg-no-repeat bg-cover fixed min-h-screen w-screen -z-50"></div> */}
      <div
        style={{
          // background: `${
          //   pokemon.types &&
          //   `linear-gradient(45deg, ${types[pokemon.types[0].type.name][1]}, ${
          //     types[pokemon.types[0].type.name][0]
          //   })`
          // }`,
          backgroundColor:
            pokemon.types && types[pokemon.types[0].type.name][1],
        }}
        className="bg-no-repeat bg-cover fixed min-h-screen w-screen -z-50"
      ></div>

      <main>
        <div className={`h-[150px] flex items-center  justify-start mx-16`}>
          <Link href="/">
            <a
              className={
                pokemon.types &&
                `text-3xl w-full text-${hexToGrayscale(
                  types[pokemon.types[0].type.name][1]
                )}`
              }
            >
              <h1 className="text-center text-5xl w-full">PokéStop</h1>
            </a>
          </Link>
        </div>
        <section
          className={
            pokemon.types &&
            `text-${hexToGrayscale(types[pokemon.types[0].type.name][1])}`
          }
        >
          <div className="h-full mt-8">
            <PokemonStats
              pokemon={pokemon}
              details={details}
              description={description}
            />
          </div>
        </section>

        {/* Info */}
        <section className="p-16 mt-8 bg-[#fff] shadow-2xl  rounded-t-[50px]"></section>
      </main>

      <footer></footer>
    </div>
  );
}
