import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Card from "../components/PokemonCard";
import React, { useState, useEffect } from "react";
import axios from "axios";

export default function Home() {
  const [pokemons, setPokemons] = useState([]);
  const [load, setLoad] = useState(
    "https://pokeapi.co/api/v2/pokemon/?offset=0&limit=40"
  );

  useEffect(() => {
    axios
      .get(load)
      .then((res) => {
        const getPokemons = async () => {
          try {
            const fetchPokemonPromises = await res.data.results.map((pokemon) =>
              axios.get(pokemon.url)
            );
            Promise.all(fetchPokemonPromises).then((values) => {
              setPokemons([...pokemons, ...values.map((value) => value.data)]);
            });
          } catch (err) {
            console.log(err);
          }
        };
        getPokemons();
      })
      .catch((err) => console.log(err));
  }, []);

  return (
    <div>
      <Head>
        <title>PokéStop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[url('../public/assets/background.jpg')] bg-no-repeat bg-cover fixed min-h-screen w-screen -z-50"></div>
      <main>
        <Navbar />
        <div className="my-12 mx-16 flex justify-center">
          <div className=" flex flex-wrap gap-12 justify-center max-w-[2000px]">
            {pokemons.map((pokemon, id) => (
              <Card key={id} pokemon={pokemon} />
            ))}
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
